### ISSUE TITLE
Display open sites on layer above closed sites

### ISSUE THREAD

**Issue by corywright** [supercharge-info/supercharge.info#83]
There are several locations on the map where closed locations are located next to, or very close to, newly opened sites. Depending on the zoom level, the Closed icon layer can obscure the Open icon.  We should make sure the Open layer is always displayed on top, and maybe even not display permanently closed by default.  Those locations aren't useful to most people, so we should consider hiding them by default.

These are locations where there are Closed markers overlaid on top of Open markers:

Villach, Austria
Nürburg Germany
Cagnes sur Mer, France
Greenwich London, UK

**Comment by paulkva** [comment]
We no longer render separate map layers per status, so I'll have to see if the order the markers are created makes a difference.

I agree it makes sense to exclude permanently closed sites from the map by default, but I think the layering/ordering is still important to fix because Open should be on top of everything else.

**Comment by paulkva** [comment]
With the latest changes on test.supercharge.info, we now exclude permanently closed sites by default on the map. Also, I spot-checked all 4 locations listed in this issue after explicitly including permanently closed sites, and they all display properly. So we should be able to close this when PR #87 is merged.
